platform :ios, '17.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end


def project_pods
  use_modular_headers!
  
  #  pod 'PhoneNumberKit'
  pod 'Kingfisher', :inhibit_warnings => true
  pod 'SwiftLint', :inhibit_warnings => true
  
  #  pod 'GoogleSignIn'
  #  pod 'FacebookCore'
  #  pod 'FacebookLogin'
  
  # KMM Core
  #  pod 'BookMeCore', :git => 'https://github.com/wizardwork/BookMe-KMM.git', :branch => 'cocoapods'
  pod 'shared', :path => '../shared'
  
end

#############################
####### Application  ########
#############################
target 'iosApp' do
  inherit! :search_paths
  project_pods
end
