platform :ios, '15.0'

def project_pods
  use_modular_headers!
  
#  pod 'PhoneNumberKit'
  pod 'Kingfisher', :inhibit_warnings => true
  pod 'SwiftLint'
  
  #  pod 'GoogleSignIn'
  #  pod 'FacebookCore'
  #  pod 'FacebookLogin'
  
  # KMM Core
  #  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
  #  pod 'BookMeCore', :git => 'https://github.com/wizardwork/BookMe-KMM.git', :branch => 'cocoapods'
  pod 'shared', :path => '../shared'
  
end

#############################
####### Application  ########
#############################
target 'BookMeNow-Develop' do
  inherit! :search_paths
  project_pods
end
